CREATE TABLE Status (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL UNIQUE
);

CREATE TABLE Subjects (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL UNIQUE
);

CREATE TABLE Questions (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	text TEXT NOT NULL,
	subject_id INTEGER NOT NULL,
	status_id INTEGER NOT NULL,
	image_path TEXT,

	FOREIGN KEY (subject_id) REFERENCES Subjects(id)
	ON UPDATE CASCADE ON DELETE CASCADE,

	FOREIGN KEY (status_id) REFERENCES Status(id)
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Answers (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	question_id INTEGER NOT NULL,
	answer_text TEXT NOT NULL,
	is_correct INTEGER NOT NULL DEFAULT 0 CHECK(is_correct IN (0,1)),
	explanation TEXT,

	FOREIGN KEY (question_id) REFERENCES Questions(id)
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL
);

CREATE TABLE Games (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	game_date TEXT NOT NULL,
	score INTEGER NOT NULL CHECK(score >= 0),

	FOREIGN KEY (user_id) REFERENCES Users(id)
	ON UPDATE CASCADE ON DELETE CASCADE
);