CREATE TABLE Statuts (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	statut TEXT NOT NULL UNIQUE
);

CREATE TABLE Sujets (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"sujet" TEXT NOT NULL UNIQUE
);

CREATE TABLE  Questions (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	text TEXT NOT NULL,
	sujet INTEGER NOT NULL,
	statut INTEGER NOT NULL,
	image_path TEXT,
	FOREIGN KEY (sujet) REFERENCES Sujets(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (statut) REFERENCES Statuts(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Reponses (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	question_id INTEGER NOT NULL,
	reponse TEXT NOT NULL,
	is_valid INTEGER NOT NULL DEFAULT 0 CHECK(is_valid IN (0,1)),
	explication TEXT,
	FOREIGN KEY (question_id) REFERENCES Questions(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE  Utilisateurs (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	nom TEXT NOT NULL,
	prenom TEXT NOT NULL,
	pseudo TEXT NOT NULL UNIQUE
);

CREATE TABLE Parties (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	utilisateur_id INTEGER NOT NULL,
	date_partie TEXT NOT NULL,
	score INTEGER NOT NULL,
	FOREIGN KEY (utilisateur_id) REFERENCES Utilisateurs(id)
	ON UPDATE CASCADE ON DELETE CASCADE
);
